package com.leaguehelper.beans;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "bb".
 */
public class ServerArea {

    private Long id;
    /** Not-null value. */
    private String sn;
    /** Not-null value. */
    private String fn;
    /** Not-null value. */
    private String snEn;

    public ServerArea() {
    }

    public ServerArea(Long id) {
        this.id = id;
    }

    public ServerArea(Long id, String sn, String fn, String snEn) {
        this.id = id;
        this.sn = sn;
        this.fn = fn;
        this.snEn = snEn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSn() {
        return sn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSn(String sn) {
        this.sn = sn;
    }

    /** Not-null value. */
    public String getFn() {
        return fn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFn(String fn) {
        this.fn = fn;
    }

    /** Not-null value. */
    public String getSnEn() {
        return snEn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSnEn(String snEn) {
        this.snEn = snEn;
    }

}
