package com.leaguehelper.dao;

import android.database.sqlite.SQLiteDatabase;

import com.greenrobot.dao.AbstractDao;
import com.greenrobot.dao.AbstractDaoSession;
import com.greenrobot.dao.identityscope.IdentityScopeType;
import com.greenrobot.dao.internal.DaoConfig;
import com.leaguehelper.beans.Hero;
import com.leaguehelper.beans.ServerArea;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see com.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig serverAreaDaoConfig;
    private final DaoConfig heroDaoConfig;

    private final ServerAreaDao serverAreaDao;
    private final HeroDao heroDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        serverAreaDaoConfig = daoConfigMap.get(ServerAreaDao.class).clone();
        serverAreaDaoConfig.initIdentityScope(type);

        heroDaoConfig = daoConfigMap.get(HeroDao.class).clone();
        heroDaoConfig.initIdentityScope(type);

        serverAreaDao = new ServerAreaDao(serverAreaDaoConfig, this);
        heroDao = new HeroDao(heroDaoConfig, this);

        registerDao(ServerArea.class, serverAreaDao);
        registerDao(Hero.class, heroDao);
    }
    
    public void clear() {
        serverAreaDaoConfig.getIdentityScope().clear();
        heroDaoConfig.getIdentityScope().clear();
    }

    public ServerAreaDao getServerAreaDao() {
        return serverAreaDao;
    }

    public HeroDao getHeroDao() {
        return heroDao;
    }

}
